DELETE FROM 'CLASS_SCHEDULE';
DELETE FROM 'GRADE';
DELETE FROM 'SUBJECT';
DELETE FROM sqlite_sequence WHERE name='CLASS_SCHEDULE';
DELETE FROM sqlite_sequence WHERE name='GRADE';
DELETE FROM sqlite_sequence WHERE name='SUBJECT';